repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.0
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: debug-statements
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.6.0
    hooks:
      - id: ansible-lint
        args:
          - "-P"
          - "shared"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--disable=R",
          ]

ci:
  skip:
    - pylint
    # Ansible-lint has a tendency to timeout in the pre-commit CI, so skip it
    - ansible-lint
