---
- name: Check that passwords are set
  assert:
    that:
      - stepca_root_password | length > 0
      - stepca_intermediate_password | length > 0
    fail_msg: "Please make sure that both stepca_root_password and stepca_intermediate_password are set!"

- name: Load distribution-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install step-ca
  include: install.yml

- name: stepca_user exists
  user:
    name: '{{ stepca_user }}'
    shell: /usr/sbin/nologin
    password: '*'
    home: '{{ stepca_home }}'
  become: yes
- name: stepca_logdir exists
  file:
    path: '{{ stepca_logdir }}'
    owner: '{{ stepca_user }}'
    group: '{{ stepca_user }}'
    state: directory
    mode: 0755
  become: yes

- name: Look for existing configuration
  stat:
    path: '{{ stepca_home }}/.step/config/ca.json'
  register: stepca_config_file
  become: yes
- name: Initialize CA
  include: init.yml
  become: yes
  become_user: '{{ stepca_user }}'
  when: not stepca_config_file.stat.exists

- name: Setup systemd service
  include: service.yml
  become: yes
