# Version of step to install. Can be latest or a specific
# github release (e.g. '0.15.3')
stepclient_version: latest

# If you want to get certificates from a step-ca server, its
# root CA cert needs to be installed in the system trust store.
# To do this automatically when installing the tool, define your
# CA urls and cert fingerprints below.
stepclient_ca_servers:
#- url: 'https://ca1.example.com:443'
#  fp: 93edf189e74fa44e9dfe74fc18d4cfd5d93b09cc210d2352171d5ea9dd70669c
