- name: Get certificate from CA
  maxhoesel.smallstep.step_ca_certificate:
    provisioner: "{{ step_acme_cert_ca_provisioner }}"
    contact: "{{ step_acme_cert_contact }}"
    crt_file: "{{ step_acme_cert_certfile_full.path }}"
    key_file: "{{ step_acme_cert_keyfile_full.path }}"
    force: yes
    name: "{{ step_acme_cert_name }}"
    not_after: "{{ step_acme_cert_duration | default(omit) }}"
    san: "{{ step_acme_cert_san }}"
    standalone: "{{ step_acme_cert_webroot_path | bool }}"
    step_cli_executable: "{{ step_cli_executable }}"
    webroot: "{{ step_acme_cert_webroot_path }}"
  become_user: "{{ step_acme_cert_user }}"
  become: yes
  environment:
    STEPPATH: "{{ _resolved_steppath }}"

- name: Cert and key permissions are set
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - "{{ step_acme_cert_keyfile_full }}"
    - "{{ step_acme_cert_certfile_full }}"
