- hosts: "ubuntu:debian"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- hosts: rockylinux:fedora
  tasks:
    # Required to prevent issues with ansible_default_ipv4 missing
    - name: Install iproute
      package:
        name: iproute
