name: Release Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  bump-galaxy-version:
    name: Update collection version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - update-release-draft
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
      - name: Set up pip and install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run updater script
        run: scripts/update-version "${{ needs.update-release-draft.outputs.version-tag }}"

      - name: Open PR for collection version update
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            galaxy.yml
          title: Update version to ${{ needs.update-release-draft.outputs.version-tag }}
          body: |
            This PR updates the galaxy.yml (and eventual other files) version to keep up with recently merged changes.

            This PR was created automatically by the release-automation workflow.
          commit-message: "Update version to ${{ needs.update-release-draft.outputs.version-tag }}"
          branch: maintenance/version-bump
          labels: pr-nochangelog
          delete-branch: true
