---
name: Version Number Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version-maintenance:
    name: Update collection version according to PR labels
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out codebase
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up pip and install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run updater script
        run: scripts/update-version "${{ steps.drafter.outputs.name }}"

      - name: Open PR for collection version update
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          add-paths: |
            galaxy.yml
            plugins/module_utils/constants.py
          title: Update collection version to ${{ steps.drafter.outputs.name }}
          body: |
            One or more changes have been merged into main since the last release.
            This PR updates the galaxy.yml (and eventual other files) version to keep up with these changes.

            Merge this PR before publishing a new release.

            This PR was created automatically by the version-maintenance workflow.
          commit-message: "Update collection version to ${{ steps.drafter.outputs.name }}"
          branch: maintenance/version-bump
          labels: chore
          delete-branch: true
